import assert from 'node:assert/strict';
import { test } from 'node:test';

import * as css from '@okikio/css';
import * as csv from '@okikio/csv';
import * as html from '@okikio/html';
import * as robots from '@okikio/robots';
import * as sitemap from '@okikio/sitemap';
import * as streams from '@okikio/streams';

/** Split encoded source at explicit byte positions so stream parsing sees realistic chunk splits. */
function byteStream(source: string, cutPoints: readonly number[]): ReadableStream<Uint8Array> {
	const bytes = new TextEncoder().encode(source);
	let start = 0;
	const chunks: Uint8Array[] = [];
	for (const end of cutPoints) {
		chunks.push(bytes.slice(start, Math.min(end, bytes.length)));
		start = Math.min(end, bytes.length);
	}
	if (start < bytes.length) chunks.push(bytes.slice(start));
	return new ReadableStream({
		start(controller) {
			for (const chunk of chunks) controller.enqueue(chunk);
			controller.close();
		},
	});
}

test('CRM import discovery preserves explicit CSV structure while composing web parsers', async () => {
	const source = [
		'Generated by CRM export',
		'Account research queue',
		'',
		'Domain,Homepage',
		'example.com,https://example.com',
		'acme.test,https://acme.test',
	].join('\r\n');

	await using document = await csv.parseStream(byteStream(source, [1, 5, 17, 31, 48, 63]), {
		headerRow: 3,
		headerScanRows: 1,
		maximumRows: 10,
	});

	assert.equal(document.headerRow, 3);
	assert.deepEqual(document.columns.map((column) => column.name), ['Domain', 'Homepage']);
	const rows = await streams.collect(document.rows, { maximumItems: 10 });
	assert.deepEqual(rows.map((row) => row.values[0]), ['example.com', 'acme.test']);

	const policy = robots.parse([
		'User-agent: *',
		'Disallow: /private/',
		'Allow: /private/pricing',
		'Sitemap: https://example.com/sitemap.xml',
	].join('\n'));
	assert.equal(robots.match(policy, { userAgent: 'KaijuResearchBot', url: 'https://example.com/private/internal' }), false);
	assert.equal(robots.match(policy, { userAgent: 'KaijuResearchBot', url: 'https://example.com/private/pricing' }), true);
	assert.deepEqual(robots.getSitemapUrls(policy), ['https://example.com/sitemap.xml']);

	const locations = sitemap.locations({
		url: 'https://example.com/sitemap.xml',
		contentType: 'application/xml',
		text: `<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://example.com/</loc></url><url><loc>https://example.com/pricing</loc></url></urlset>`,
	});
	assert.deepEqual(locations, ['https://example.com/', 'https://example.com/pricing']);

	const page = html.parse(`<!doctype html><html><head><link rel="stylesheet" href="/app.css"></head><body><main><a href="/pricing">Pricing</a></main></body></html>`);
	const link = html.selectOne(page.document, 'main a[href]');
	assert.ok(link);
	assert.equal(html.attribute(link, 'href'), '/pricing');

	const references = css.parseResources(`@font-face { src: url('/brand.woff2') } .hero { background-image: url('/hero.webp') }`);
	assert.deepEqual(references.map((reference) => [reference.kind, reference.url]), [
		['font', '/brand.woff2'],
		['image', '/hero.webp'],
	]);

	const batches: (readonly string[])[] = [];
	for await (const batch of streams.batch(locations, { maximumItems: 1 })) batches.push(batch);
	assert.deepEqual(batches, [['https://example.com/'], ['https://example.com/pricing']]);
});
