import { describe, it } from 'node:test'
import { expect } from '@std/expect'
import { parse as parseMatrix } from '@std/csv/parse'

import * as csv from './mod.ts'

describe('CSV collecting parser', () => {
	const fixtures = new URL('./fixtures/', import.meta.url)

	async function readFixture(path: string): Promise<Uint8Array> {
		return await Deno.readFile(new URL(path, fixtures))
	}

	it('detects supported delimiters and byte encodings', async () => {
		const comma = csv.parseBytes(await readFixture('representative/hubspot/companies-export.csv'))
		const semicolon = csv.parseBytes(await readFixture('edge-cases/semicolon-delimited.csv'))
		const tab = csv.parseBytes(await readFixture('edge-cases/tab-delimited.tsv'))
		const bom = csv.parseBytes(await readFixture('edge-cases/utf8-bom-non-ascii.csv'))
		const legacy = csv.parseBytes(new Uint8Array([
			0x43, 0x61, 0x66, 0xe9, 0x2c, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x0a,
			0x41, 0x63, 0x6d, 0xe9, 0x2c, 0x61, 0x63, 0x6d, 0x65, 0x2e, 0x65, 0x78,
			0x61, 0x6d, 0x70, 0x6c, 0x65,
		]))

		expect(comma.delimiter).toEqual(',')
		expect(semicolon.delimiter).toEqual(';')
		expect(tab.delimiter).toEqual('\t')
		expect(bom.encoding).toEqual('utf-8-bom')
		expect(legacy.encoding).toEqual('windows-1252')
		expect(legacy.diagnostics.some((diagnostic) => diagnostic.code === 'legacy-encoding')).toBeTruthy()
	})

	it('preserves logical rows and identifies an instructional preamble structurally', async () => {
		const multiline = csv.parseBytes(await readFixture('edge-cases/multiline-quotes-and-commas.csv'))
		const pipedrive = csv.parseBytes(await readFixture('official/pipedrive-sample-official.csv'))

		expect(multiline.rows.length).toEqual(2)
		expect(multiline.rows[0]?.values.some((value) => value.includes('\n'))).toBeTruthy()
		expect(pipedrive.headerRow > 1).toBeTruthy()
		expect(pipedrive.diagnostics.some((diagnostic) => diagnostic.code === 'preamble-skipped')).toBeTruthy()
	})

	it('disambiguates headers and preserves source cells as strings', async () => {
		const duplicate = csv.parseBytes(await readFixture('edge-cases/duplicate-and-empty-headers.csv'))
		const identifiers = csv.parseBytes(await readFixture('edge-cases/leading-zero-identifiers.csv'))
		const formulas = csv.parseBytes(await readFixture('edge-cases/formula-injection.csv'))

		expect(new Set(duplicate.columns.map((column) => column.key)).size).toEqual(duplicate.columns.length)
		expect(duplicate.diagnostics.some((diagnostic) => diagnostic.code === 'blank-header')).toBeTruthy()
		expect(duplicate.diagnostics.some((diagnostic) => diagnostic.code === 'duplicate-header')).toBeTruthy()
		expect(identifiers.rows[0]?.values.some((value) => /^0\d+/.test(value))).toBeTruthy()
		expect(formulas.rows.flatMap((row) => row.values).some((value) => value.startsWith('='))).toBeTruthy()
		expect(formulas.diagnostics.some((diagnostic) => diagnostic.code === 'spreadsheet-formula')).toBeTruthy()
	})

	it('accepts a one-column domain import', () => {
		const document = csv.parse('Domain\nexample.com\nopenai.com\n')

		expect(document.columns.map((column) => column.key)).toEqual(['domain'])
		expect(document.rows.map((row) => row.values)).toEqual([['example.com'], ['openai.com']])
	})

	it('supports explicit dialect and header-row overrides', () => {
		const document = csv.parse([
			'Generated by CRM',
			'Company;Domain',
			'Northstar;northstar.example',
		].join('\n'), { delimiter: ';', headerRow: 2 })

		expect(document.headerRow).toEqual(2)
		expect(document.delimiter).toEqual(';')
		expect(document.rows[0]?.values).toEqual(['Northstar', 'northstar.example'])
	})

	it('enforces each collecting safety limit at the public boundary', () => {
		expect(() => csv.parse('Company,Domain\nOne,one.example\nTwo,two.example', { maximumRows: 1 }))
			.toThrow(csv.CsvParseError)
		expect(() => csv.parse('Company,Domain\nOne,one.example', { maximumColumns: 1 }))
			.toThrow(csv.CsvParseError)
		expect(() => csv.parse('Company,Domain\nNorthstar,northstar.example', { maximumCellCharacters: 5 }))
			.toThrow(csv.CsvParseError)
		expect(() => csv.parseBytes(new TextEncoder().encode('Company,Domain\nNorthstar,northstar.example'), { maximumBytes: 8 }))
			.toThrow(csv.CsvParseError)
		expect(() => csv.parse('Company,Domain\nNorthstar,northstar.example', { maximumCharacters: 8 }))
			.toThrow(csv.CsvParseError)
	})

	it('rejects empty and malformed input', async () => {
		const empty = await readFixture('edge-cases/empty-file.csv')
		const malformed = await readFixture('edge-cases/malformed-unclosed-quote.csv')
		expect(() => csv.parseBytes(empty)).toThrow(csv.CsvParseError)
		expect(() => csv.parseBytes(malformed)).toThrow(csv.CsvParseError)
	})

	it('matches the supplied fixture acceptance matrix', async () => {
		const matrix = parseMatrix(await Deno.readTextFile(new URL('validation.csv', fixtures)), { skipFirstRow: true }) as Record<string, string>[]
		expect(matrix.length).toEqual(41)
		for (const fixture of matrix) {
			const path = fixture.path
			const expected = fixture.expected_outcome
			if (!path || !expected) throw new Error('Fixture matrix rows require path and expected_outcome.')
			let error: unknown
			try {
				csv.parseBytes(await readFixture(path), { fileName: path })
			} catch (cause) {
				error = cause
			}
			if (expected === 'reject') expect(error instanceof csv.CsvParseError).toBeTruthy()
			else expect(error).toEqual(undefined)
		}
	})
})
